# Main compose file for ROS-master with the container from Dockerhub.
version: '2.1'

services:
  motor_controller:
    # image: windesheimwinny/motor_controller:latest
    build: ./docker
    command: roslaunch telop_twist_joy telop.launch
    networks:
      - ros
    restart: always
    volumes:
      - ./:/root/wtgd

networks:
  ros:
