# Main compose file for ROS-master with the container from Dockerhub.
version: '2.1'

services:
  motor_controller:
    image: windesheimwinny/motor_controller:latest
    networks:
      - ros
    restart: always

networks:
  ros:
